name: flutter_app_1771020152
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
    
  # --- CÁC THƯ VIỆN CHÍNH ---
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.1.0      
  shared_preferences: ^2.2.2
  intl: ^0.18.1   # Thư viện để format tiền tệ và ngày tháng
  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 

flutter:
  uses-material-design: true

  # --- CẤU HÌNH FONT ICON OFFLINE (SỬA LỖI Ô VUÔNG) ---
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.otf
  # ----------------------------------------------------